server.port=8080
server.http2.enabled=false
server.shutdown=graceful
server.tomcat.accesslog.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
spring.lifecycle.timeout-per-shutdown-phase=5s
spring.threads.virtual.enabled=false
spring.main.banner-mode=off
spring.main.log-startup-info=false
spring.sql.init.mode=never
logging.level.root=OFF
